{"timestamp": "2025-05-15T14:33:11.877383", "ticker": "2784", "error_type": "Exception", "error_message": "取引パスワード入力欄が見つかりません", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\ryosh\\enrich_me\\project\\modules\\trading\\sbi\\operations\\order_manager\\settlement_manager.py\", line 259, in _process_single_settlement_order\n    await retry_handler.execute_with_retry(self._send_order)\n  File \"C:\\Users\\ryosh\\enrich_me\\project\\modules\\trading\\sbi\\operations\\order_manager\\settlement_manager.py\", line 45, in execute_with_retry\n    raise last_exception\n  File \"C:\\Users\\ryosh\\enrich_me\\project\\modules\\trading\\sbi\\operations\\order_manager\\settlement_manager.py\", line 30, in execute_with_retry\n    return await func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ryosh\\enrich_me\\project\\modules\\trading\\sbi\\operations\\order_manager\\settlement_manager.py\", line 390, in _send_order\n    raise Exception(\"取引パスワード入力欄が見つかりません\")\nException: 取引パスワード入力欄が見つかりません\n", "page_url": null, "page_title": null}
